Tinkov/catalog_epic_2-3
Skoch33/iOS-FakeNFT-StarterProject-Public pull request #33
Opened 2023-10-15 11:52 UTC by AlekseiTinkov

2023-10-16 21:12 UTC, Konstantin-vetro requested changes
Твоя верстка кода читаема и мне понятна) оставил небольшие замечания по улучшению читаемости кода

2023-10-16 21:12 UTC, Konstantin-vetro commented on FakeNFT/WebView/WebViewController.swift
> +        webView.load(URLRequest(url: url))
Можно декомпозировать данный метод на несколько функций, что думаешь? Например можно реализовать методы setupNavigationController() и showWebsiteAuthor(), так код станет нагляднее и более читаемым.

```
override func viewDidLoad() {
    super.viewDidLoad()
    setupWebView()
    setupNavigationController()
    showWebsiteAuthor()
}
```

2023-10-16 21:12 UTC, Konstantin-vetro commented on FakeNFT/Catalog/Collection/CollectionViewController.swift
> +        }
Строка длинная можно попробовать так:
```
guard let cell = collectionView.dequeueReusableCell(
      withReuseIdentifier: CollectionViewCell.identifier,
      for: indexPath
 ) as? CollectionViewCell else {
       assertionFailure("Error get cell")
       return .init()
    }
```

2023-10-16 21:12 UTC, Konstantin-vetro commented on FakeNFT/Catalog/Collection/CollectionViewController.swift
> +        collectionView.heightAnchor.constraint(equalToConstant: collectionHeight).isActive = true
Чтобы не загромождать viewDidLoad() для лучшей читаемости кода можно реализовать один метод, например setupViews() в котором будут вызваны все методы по настройке вьюшек, вызвав его во viewDidLoad.  В будущем если добавиться методы логики то достаточно сложно будем удержать внимание на всех операциях и условиях.

Например так:
```
override func viewDidLoad() {
    super.viewDidLoad()
    setupNavigationBar()     
    setupViews()
    }

private func setupViews() {
    setupScrollView()
    setupCoverImage()
    setupNameLabel()
    setupAuthorTitleLabel()
    setupAuthorNameLabel()
    setupDescriptionLabel()
    setupCollectionView()
    
    let collectionHeight = (Const.cellHeight + Const.lineMargins) * ceil(CGFloat(collectionCount) / Const.cellCols)
    collectionView.heightAnchor.constraint(equalToConstant: collectionHeight).isActive = true
}

private func setupNavigationController() {
    let backItem = UIBarButtonItem()
    backItem.title = nil
    backItem.tintColor = .nftBlack
    navigationController?.navigationBar.topItem?.backBarButtonItem = backItem
}
```

2023-10-16 21:12 UTC, Konstantin-vetro commented on FakeNFT/Catalog/Collection/CollectionViewController.swift
> +        scrollView.addSubview(nameLabel)
Так как эти строки повторяются в методах настройки вьюшек, можно вынести их в метод setupViews(), так код станет проще и более читаемым, согласно принципу DRY, а реализованные в методах удалить
```
[coverImage, nameLabel, authorTitleLabel, 
authorNameLabel, descriptionLabel, collectionView].forEach {
    $0.translatesAutoresizingMaskIntoConstraints = false
    scrollView.addSubview($0)
}
```

2023-10-16 21:12 UTC, Konstantin-vetro commented on FakeNFT/Catalog/Collection/CollectionViewController.swift
> +    let collectionCount = 19
Может сделать ее private, раз она используется только в этом классе? Хотя она наверно для проверки)

2023-10-16 21:12 UTC, Konstantin-vetro commented on FakeNFT/Catalog/Collection/CollectionViewCell.swift
> +    private var cardImage: UIImageView = {
Можно сделать эти свойства ленивыми, что позволит уменьшить нагрузку на память и ускорить производительность приложения, так как они будут проинициализированы только при первом обращении к ним

2023-10-16 21:12 UTC, Konstantin-vetro commented on FakeNFT/Catalog/Collection/CollectionViewCell.swift
> +        contentView.addSubview(cardImage)
Так как эти строки повторяются в методах настроек вью, можно вынести их в отдельный метод setupViews() или в override init(frame: CGRect), так код станет проще и более читаемым, согласно принципу DRY, а реализованные в методах удалить

```
[cardImage, likeButton, starsView, 
nameLabel, priceLabel, cardButton].forEach {
    $0.translatesAutoresizingMaskIntoConstraints = false
    contentView.addSubview($0)
}
```

2023-10-16 21:12 UTC, Konstantin-vetro commented on FakeNFT/Catalog/Collection/CollectionViewController.swift
> +    private var scrollView: UIScrollView = {
Так же можно сделать эти свойства ленивыми

2023-10-16 22:22 UTC, AlekseiTinkov commented on FakeNFT/Catalog/Collection/CollectionViewController.swift
> +        }
Исправил. Спасибо за пример.

2023-10-16 22:22 UTC, AlekseiTinkov commented on FakeNFT/Catalog/Collection/CollectionViewController.swift
> +        collectionView.heightAnchor.constraint(equalToConstant: collectionHeight).isActive = true
Исправил.

2023-10-16 22:23 UTC, Konstantin-vetro approved these changes

2023-10-16 22:23 UTC, AlekseiTinkov commented on FakeNFT/Catalog/Collection/CollectionViewController.swift
> +        scrollView.addSubview(nameLabel)
Удобный паттерн. Буду использовать и дальше.

2023-10-16 22:23 UTC, AlekseiTinkov commented on FakeNFT/Catalog/Collection/CollectionViewController.swift
> +    let collectionCount = 19
Это временная переменная. При внедрении ViewModel планирую избавиться от нее.

2023-10-16 22:23 UTC, AlekseiTinkov commented on FakeNFT/Catalog/Collection/CollectionViewCell.swift
> +    private var cardImage: UIImageView = {
Это временные переменные. При внедрении логики состояния ячейки будут задаваться через конфигуратор.

2023-10-16 22:23 UTC, AlekseiTinkov commented on FakeNFT/Catalog/Collection/CollectionViewCell.swift
> +        contentView.addSubview(cardImage)
Применил.

2023-10-16 22:24 UTC, AlekseiTinkov commented on FakeNFT/WebView/WebViewController.swift
> +        webView.load(URLRequest(url: url))
Декомопозировал. Теперь читается легче.

2023-10-16 22:30 UTC, AlekseiTinkov commented on FakeNFT/Catalog/Collection/CollectionViewController.swift
> +    private var scrollView: UIScrollView = {
Поправил во всех местах здесь и в CollectionViewCell

2023-10-19 06:55 UTC, Helvetii951 commented on FakeNFT/Catalog/Collection/CollectionViewCell.swift
> +    var cardState = false
Тут неоднозначные нэйминги.

1. `CollectionViewCell` - очень абстратно. Не сразу поймешь какой коллекции эта ячейка.
2. `likeState` я бы переименовал в isLiked.
3. `cardState`. Скорее всего cart. И тут я бы тоже переименовал в `isInCart`

2023-10-19 06:55 UTC, Helvetii951 commented on FakeNFT/WebView/WebViewController.swift
> +    }
Клево, что ты реализовал кастомный контроллер с веб-вью. 

Здесь можно использовать [sfsafariviewcontroller](https://developer.apple.com/documentation/safariservices/sfsafariviewcontroller). В несколько строчек можно создать экземпляр, передать урл и отобразить веб-страницу. Плюс мы получим плюшки - почти все, что есть в Safari. Дизайн будет чуть отличатся.

2023-10-19 06:55 UTC, Helvetii951 commented on FakeNFT/Catalog/Collection/CollectionViewController.swift
> +    }
Тут я тоже я бы порекомендовал поменять нэйминг. Не совсем понятно что за лэйбл. Например, так `didTapUserNameLabel`

2023-10-19 06:55 UTC, Helvetii951 commented on FakeNFT/en.lproj/Localizable.strings
> +"Collection.AuthorLabel" = "Author of the collection:";
Тут тоже название строки лучше поменять. `Collection.` звучит очень абстрактно.

2023-10-19 20:14 UTC, AlekseiTinkov commented on FakeNFT/WebView/WebViewController.swift
> +    }
Спасибо, изучу

2023-10-19 20:15 UTC, AlekseiTinkov commented on FakeNFT/Catalog/Collection/CollectionViewCell.swift
> +    var cardState = false
Это временные переменные. Только для тестирования ячейки. В ближайшее время они уйдут из кода.

2023-10-19 20:15 UTC, AlekseiTinkov commented on FakeNFT/Catalog/Collection/CollectionViewController.swift
> +    }
Учел

2023-10-19 20:15 UTC, AlekseiTinkov commented on FakeNFT/en.lproj/Localizable.strings
> +"Collection.AuthorLabel" = "Author of the collection:";
учел

2023-10-19 20:49 UTC, merged