Kocherga/profile epic_2-3
Skoch33/iOS-FakeNFT-StarterProject-Public pull request #35
Opened 2023-10-17 14:55 UTC by Skoch33

Эпик: Профиль
Архитектура: MVVM
Верстка кодом

Файл декомпозиции:
https://github.com/Skoch33/iOS-FakeNFT-StarterProject-Public/blob/kocherga/profile-2-3/Doc/Profile.md
Task tracker:
https://github.com/users/Skoch33/projects/2

- Реализация NavigationBar (est: 30 min; fact: 20 min)
- Создание UITableView (est: 60 min; fact: 30 min)
- Верстка кастомной ячейки (est: 50 min; fact: 40 min)
- Реализация функции сортировки (est: 90 min; fact: 40 min)
- Создание модели (est: 20 min; fact: 20 min)
- Создание сетевого слоя (est: 60 min; fact: 40 min)

`Total:` est: 310 min; fact: 190 min

2023-10-17 21:52 UTC, AlekseiTinkov requested changes
Привет! Отличный код! Круто, что сразу ввел протокол для ViewModel, так будет удобнее делать тесты. Так же очень понравилось как ты грузишь информацию о nft одновременно в нескольких потоках, используя DispatchGroup(). К сожалению в коде нарушен принцип MVVM - ViewModel не должен ничего знать об UI, включая ProgressHUD. Предлагаю попробовать исправить это.

2023-10-17 21:52 UTC, AlekseiTinkov commented on FakeNFT/Profile/UserNFTScreen/Views/NFTCell.swift
> +import Cosmos
Классная библиотека. Но сейчас у желтых и серых звезд разный размер. Возможно проблема просто в асетах. Можно обойтись и вовсе без библиотеки, например создав массив из 5ти UIImageView, вставленных в UIStackView.

2023-10-17 21:52 UTC, AlekseiTinkov commented on FakeNFT/Profile/UserNFTScreen/Views/NFTCell.swift
> +        self.nftImageView.kf.setImage(with: URL(string: nft.images[0]))
Обрати внимание - в Фигме есть изображения заглушки для не загрузившихся nft

2023-10-17 21:52 UTC, AlekseiTinkov commented on FakeNFT/Profile/UserNFTScreen/Views/UserNFTViewController.swift
> +        view.backgroundColor = .white
Для корректного отображения темной темы здесь стоит указать .nftWhite

2023-10-17 21:52 UTC, AlekseiTinkov commented on FakeNFT/Profile/UserNFTScreen/UserNFTViewModel.swift
> +        ProgressHUD.show(NSLocalizedString("ProgressHUD.loading", comment: ""))
ViewModel знает подробности UI - сама показывает/скрывает ProgressHUD. В MVVM это не ее обязанность. Здесь можно создать наблюдаемую сущность, например isLoading и в зависимости от ее состояния отображать ProgressHUD во ViewController

2023-10-17 21:52 UTC, AlekseiTinkov commented on FakeNFT/Models/Network/NFTNetworkRequests.swift
> +        URL(string: "https://651ff0d9906e276284c3c20a.mockapi.io/api/v1/nft/\(nftID)")
Базовую часть URL лучше вынести в отдельную константу и использовать по всему проекту

2023-10-18 09:43 UTC, Skoch33 commented on FakeNFT/Profile/UserNFTScreen/Views/NFTCell.swift
> +import Cosmos
Исправил!

2023-10-18 09:43 UTC, Skoch33 commented on FakeNFT/Profile/UserNFTScreen/Views/UserNFTViewController.swift
> +        view.backgroundColor = .white
Исправил!

2023-10-18 10:46 UTC, AlekseiTinkov approved these changes

2023-10-18 12:10 UTC, So1ovyov commented on FakeNFT/DesignSystem/UIViewController + Extensions.swift
> +        let backButton = UIBarButtonItem(image: UIImage(named: "backward"),
Кажется избыточным, можно например:
```
    func setupCustomBackButton() {
        navigationItem.leftBarButtonItem = UIBarButtonItem(
            image: UIImage(named: "backward"),
            style: .plain,
            target: self,
            action: #selector(self.customBackAction)
        )
    }
```

2023-10-18 12:11 UTC, So1ovyov commented on FakeNFT/Helpers/AlertService.swift
> +        let alertController = UIAlertController(title: model.title, message: model.message, preferredStyle: model.style)
Давай длинные строки дробить, чтобы легче читалось:
```
        let alertController = UIAlertController(
            title: model.title,
            message: model.message,
            preferredStyle: model.style
        )

```

2023-10-18 12:12 UTC, So1ovyov commented on FakeNFT/Models/Network/NFTNetworkRequests.swift
> +        URL(string: "https://651ff0d9906e276284c3c20a.mockapi.io/api/v1/nft/\(nftID)")
Хорошая идея, например `private enum Constants`

2023-10-18 12:14 UTC, So1ovyov commented on FakeNFT/Profile/EditScreen/EditingViewController.swift
> +    private func changePhotoTapped() {
Очень большой метод, давай декомпозируем и вынесем какую-то логику.

2023-10-18 12:15 UTC, So1ovyov commented on FakeNFT/Profile/EditScreen/EditingViewModel.swift
> +    init(profileService: ProfileService, imageValidator: ImageValidatorProtocol = ImageValidator()) {
Длинная строка:
```
    init(
        profileService: ProfileService,
        imageValidator: ImageValidatorProtocol = ImageValidator()
    ) {
        self.profileService = profileService
        self.imageValidator = imageValidator
    }
```

2023-10-18 12:15 UTC, So1ovyov commented on FakeNFT/Profile/EditScreen/EditingViewModel.swift
> +    init(profileService: ProfileService, imageValidator: ImageValidatorProtocol = ImageValidator()) {
Также давай в ините не задавать дефолтное значение, лучше это делать в месте где ты объявляешь `EditingViewModel`

2023-10-18 12:17 UTC, So1ovyov commented on FakeNFT/Profile/ProfileScreen/ProfileViewModel.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(profileUpdated), name: NSNotification.Name("profileUpdated"), object: nil)
Длинная конструкция, давай дробить

2023-10-18 12:18 UTC, So1ovyov commented on FakeNFT/Profile/UserNFTScreen/UserNFTViewModel.swift
> +        ProgressHUD.show(NSLocalizedString("ProgressHUD.loading", comment: ""))
Верно подмечено, проверь свои ViewModel-и в проекте. У них должны быть методы которые дергают ручки во ViewController

2023-10-18 12:19 UTC, So1ovyov commented on FakeNFT/Profile/UserNFTScreen/UserNFTViewModel.swift
> +                    print("Failed to fetch NFT with ID \(element): \(error)")
Было бы круто отображать ошибки в алертах пользователю, чтобы он понимал что происходит в приложении. Принт он не увидит к сожалению

2023-10-18 12:19 UTC, So1ovyov commented on FakeNFT/Profile/UserNFTScreen/Views/NFTCell.swift
> +            view.image = UIImage()
Здесь нет никакой картинки, из-за этого звезд рейтинга нет на экране `Мои NFT`

2023-10-18 12:22 UTC, So1ovyov commented on FakeNFT/Profile/UserNFTScreen/Views/NFTCell.swift
> +    private let nftImageView = ViewFactory.shared.createNFTImageView()
Почему ViewFactory сделан как Singletone ? Вот рассуждение о том почему это плохо [ссылка](https://stackoverflow.com/questions/35500492/how-to-create-a-uiview-singleton-in-swift)

Давай избавляться от Singletone в проекте для создания верстки. Это плохая затея которая может отработать не корректно.

2023-10-18 12:22 UTC, So1ovyov commented on FakeNFT/Profile/UserNFTScreen/Views/NFTCell.swift
> +        self.nftImageView.kf.setImage(with: URL(string: nft.images[0]))
Обязательно нужна заглушка для случая когда картинки не нашлось

2023-10-18 12:23 UTC, So1ovyov commented on FakeNFT/Profile/UserNFTScreen/Views/UserNFTViewController.swift
> +            print("error to get NFT")
Давай избавимся от print-ов для дебага в проекте

2023-10-18 12:26 UTC, So1ovyov commented on FakeNFT/Profile/ProfileScreen/Views/ProfileViewController.swift
>                  switch result {
Тут ниже код:
```
[self!.editButton, self!.profileImageView, self!.userNameLabel, self!.userDescriptionLabel, self!.userWebSiteTextView, self!.profileTableView].forEach { $0.isHidden = false }
```
force self нельзя использовать
Вообще любой force unwrap/property/cast запрещен

2023-10-18 16:16 UTC, Skoch33 commented on FakeNFT/DesignSystem/UIViewController + Extensions.swift
> +        let backButton = UIBarButtonItem(image: UIImage(named: "backward"),
Исправлено

2023-10-18 16:16 UTC, Skoch33 commented on FakeNFT/Helpers/AlertService.swift
> +        let alertController = UIAlertController(title: model.title, message: model.message, preferredStyle: model.style)
Исправлено

2023-10-18 16:16 UTC, Skoch33 commented on FakeNFT/Profile/ProfileScreen/ProfileViewModel.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(profileUpdated), name: NSNotification.Name("profileUpdated"), object: nil)
Исправлено

2023-10-18 16:17 UTC, Skoch33 commented on FakeNFT/Profile/UserNFTScreen/Views/NFTCell.swift
> +            view.image = UIImage()
Исправлено, была ошибка в написании имени

2023-10-18 16:17 UTC, Skoch33 commented on FakeNFT/Profile/UserNFTScreen/Views/NFTCell.swift
> +    private let nftImageView = ViewFactory.shared.createNFTImageView()
Спасибо!
Избавился от этого файла

2023-10-18 16:18 UTC, Skoch33 commented on FakeNFT/Profile/UserNFTScreen/Views/NFTCell.swift
> +        self.nftImageView.kf.setImage(with: URL(string: nft.images[0]))
Исправлено

2023-10-18 19:53 UTC, merged